import CertifiedAffine.TseitinCNFData

/-!
# Declarative Parity-Encoded CNF Class

This module starts the v0.2 proof lane. The semantic theorem here is not the
main extractor result: per-assignment equivalence composes over appended CNFs by
ordinary conjunction reasoning. The value of the class is that later extractor
completeness can quantify over CNFs not generated by a single encoder.
-/

namespace CertifiedAffine
namespace TseitinCNFData

namespace ParityEncoded

/-- Compact GF(2) formula type at fixed ambient variable count. -/
abbrev GF2Formula (m : Nat) :=
  List (ResoplusPDT.ParityClause (Basic.CNF.mk m))

/-- Variables appearing in one ordinary CNF clause. -/
def clauseSupport {m : Nat} (c : CNFModel.Clause m) : List (Fin m) :=
  c.map (fun l => l.var)

/-- Variables appearing in an ordinary CNF. -/
def cnfSupport {m : Nat} (f : CNFModel.CNF m) : List (Fin m) :=
  f.bind clauseSupport

/--
Disjoint ordinary-CNF support. The semantic theorem below does not need this;
it is carried now because extractor completeness over unions will need it.
-/
def DisjointSupport {m : Nat} (f g : CNFModel.CNF m) : Prop :=
  forall v : Fin m, List.Mem v (cnfSupport f) ->
    List.Mem v (cnfSupport g) -> False

/-- GF(2) CNF satisfaction over appended equation lists splits into both sides. -/
theorem gf2Sat_append_iff
    {m : Nat} (a : CNFModel.Assignment m)
    (s t : GF2Formula m) :
    ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a (s ++ t) <->
      ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a s /\
        ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a t := by
  constructor
  case mp =>
    intro hsat
    exact
      And.intro
        (fun c hc => hsat c (List.mem_append_left t hc))
        (fun c hc => hsat c (List.mem_append_right s hc))
  case mpr =>
    intro hsat c hc
    exact
      match List.mem_append.1 hc with
      | Or.inl hs => hsat.1 c hs
      | Or.inr ht => hsat.2 c ht

/-- GF(2) CNF satisfaction is invariant under equation-list permutation. -/
theorem gf2Sat_iff_of_perm
    {m : Nat} {a : CNFModel.Assignment m}
    {s t : GF2Formula m}
    (hperm : List.Perm s t) :
    ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a s <->
      ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a t := by
  constructor
  case mp =>
    intro hsat c hc
    exact hsat c (hperm.symm.subset hc)
  case mpr =>
    intro hsat c hc
    exact hsat c (hperm.subset hc)

/-- Singleton GF(2) formula satisfaction is just satisfaction of its equation. -/
theorem gf2Sat_singleton_iff_clauseSat
    {m : Nat} (a : CNFModel.Assignment m)
    (c : ResoplusPDT.ParityClause (Basic.CNF.mk m)) :
    ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a [c] <->
      ResoplusPDT.ClauseSat (F := Basic.CNF.mk m) a c := by
  constructor
  case mp =>
    intro hsat
    exact hsat c (List.Mem.head [])
  case mpr =>
    intro hsat d hd
    cases hd with
    | head =>
        exact hsat
    | tail _ htail =>
        cases htail

/--
Declarative class of CNFs that are known to be clause-complete parity
expansions. The `union` constructor intentionally stores disjoint support for
future extractor completeness; semantic soundness does not use it. The
`append` constructor is the semantic gluing rule for overlapping parity blocks,
such as Tseitin vertex equations that share edge variables.
-/
inductive Class (m : Nat) :
    CNFModel.CNF m -> GF2Formula m -> Prop
  | empty :
      Class m [] []
  | atom (vars : List (Fin m)) (charge : Bool) (f : CNFModel.CNF m)
      (hperm : List.Perm f (clausesForVertex vars charge)) :
      Class m f [parityClauseForVertex vars charge]
  | append {f g : CNFModel.CNF m} {s t : GF2Formula m}
      (hf : Class m f s) (hg : Class m g t) :
      Class m (f ++ g) (s ++ t)
  | union {f g : CNFModel.CNF m} {s t : GF2Formula m}
      (hf : Class m f s) (hg : Class m g t)
      (hdisjoint : DisjointSupport f g) :
      Class m (f ++ g) (s ++ t)
  | cnf_perm {f g : CNFModel.CNF m} {s : GF2Formula m}
      (hperm : List.Perm f g) (hf : Class m f s) :
      Class m g s
  | gf2_perm {f : CNFModel.CNF m} {s t : GF2Formula m}
      (hperm : List.Perm s t) (hf : Class m f s) :
      Class m f t

/--
Semantic soundness for the declarative class. This is the intentionally easy
layer: the union case is just CNF append splitting plus GF(2) append splitting.
-/
theorem Class.sound
    {m : Nat} {f : CNFModel.CNF m} {s : GF2Formula m}
    (h : Class m f s) :
    forall a : CNFModel.Assignment m,
      CNFModel.cnfSat a f <->
        ResoplusPDT.CNFSat (F := Basic.CNF.mk m) a s := by
  induction h with
  | empty =>
      intro a
      constructor
      case mp =>
        intro _hsat c hc
        cases hc
      case mpr =>
        intro _hsat c hc
        cases hc
  | atom vars charge f hperm =>
      intro a
      have hblock :
          CNFModel.cnfSat a (clausesForVertex vars charge) <->
            ResoplusPDT.ClauseSat
              (F := Basic.CNF.mk m) a
              (parityClauseForVertex vars charge) :=
        tseitinVertexBlock_gf2SemanticPreservation
          (m := m) a (vars := vars) (charge := charge)
      exact
        Iff.trans
          (cnfSat_iff_of_perm (a := a) hperm)
          (Iff.trans hblock
            (gf2Sat_singleton_iff_clauseSat a
              (parityClauseForVertex vars charge)).symm)
  | append _hf _hg ihf ihg =>
      intro a
      constructor
      case mp =>
        intro hsat
        have hsplit := (cnfSat_append_iff a _ _).1 hsat
        exact
          (gf2Sat_append_iff a _ _).2
            (And.intro
              ((ihf a).1 hsplit.1)
              ((ihg a).1 hsplit.2))
      case mpr =>
        intro hsat
        have hsplit := (gf2Sat_append_iff a _ _).1 hsat
        exact
          (cnfSat_append_iff a _ _).2
            (And.intro
              ((ihf a).2 hsplit.1)
              ((ihg a).2 hsplit.2))
  | union _hf _hg _hdisjoint ihf ihg =>
      intro a
      constructor
      case mp =>
        intro hsat
        have hsplit := (cnfSat_append_iff a _ _).1 hsat
        exact
          (gf2Sat_append_iff a _ _).2
            (And.intro
              ((ihf a).1 hsplit.1)
              ((ihg a).1 hsplit.2))
      case mpr =>
        intro hsat
        have hsplit := (gf2Sat_append_iff a _ _).1 hsat
        exact
          (cnfSat_append_iff a _ _).2
            (And.intro
              ((ihf a).2 hsplit.1)
              ((ihg a).2 hsplit.2))
  | cnf_perm hperm _hf ih =>
      intro a
      exact Iff.trans (cnfSat_iff_of_perm (a := a) hperm).symm (ih a)
  | gf2_perm hperm _hf ih =>
      intro a
      exact Iff.trans (ih a) (gf2Sat_iff_of_perm (a := a) hperm)

end ParityEncoded
end TseitinCNFData
end CertifiedAffine
